version: '3.4'

x-main: &main
  tty: true
  stdin_open: true
  build: .
  volumes:
    - '.:/app'
  environment:
    DB_HOST: postgres
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: 'postgres:13.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis'
    volumes:
      - 'redis:/data'

  app:
    <<: *main

volumes:
  postgres:
  redis:
